version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: arn:aws:ecs:ap-south-1:815349656216:task-definition/book-now-demo:3
        LoadBalancerInfo:
          ContainerName: BookNowApplication
          ContainerPort: 8080
