version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo Building Docker image for Spring Boot application...
      - docker build -t $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/booknow:latest .

  post_build:
    commands:
      - echo Pushing Docker image to Amazon ECR...
      - docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/booknow:latest

artifacts:
  files: '**/*'
  discard-paths: yes
  s3:
    bucket: booknowproject
    path: booknowproject/artifacts